export const rooms = [
  {
    name: "Sydney Boutique Hotel",
    pricePerNight: 168,
    description: "Your holiday starts from here!",
    address: "114 Darlinghurst Rd, Darlinghurst NSW 2010",
    guestCapacity: 1,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: false,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "ttday/sydney2_z6r6hx",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216599/ttday/sydney2_z6r6hx.png",
      },
      {
        public_id: "ttday/554737730_cjpwsm",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216593/ttday/554737730_cjpwsm.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Fremantle Prison YHA",
    pricePerNight: 242,
    description: "This is Fremantle.",
    address: "6A The Terrace, Fremantle WA 6160",
    guestCapacity: 2,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "ttday/554737738_thdndt",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216593/ttday/554737738_thdndt.jpg",
      },
      {
        public_id: "ttday/perth4_isgq7q",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216597/ttday/perth4_isgq7q.jpg",
      },
    ],
    category: "Twins",
    reviews: [],
  },
  {
    name: "Crown Perth",
    pricePerNight: 85,
    description: "You win, you stay, you millionaire",
    address: "Great Eastern Hwy, Burswood WA 6100",
    guestCapacity: 3,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: true,
    isRoomCleaning: false,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "ttday/554737721_nyozgb",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216591/ttday/554737721_nyozgb.jpg",
      },
      {
        public_id: "ttday/perth3_nho16o",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216595/ttday/perth3_nho16o.jpg",
      },
      {
        public_id: "ttday/554737697_jw7cck",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216590/ttday/554737697_jw7cck.jpg",
      },
      {
        public_id: "ttday/33548903_grgkto",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216586/ttday/33548903_grgkto.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Hilton Garden Inn Busselton",
    pricePerNight: 95,
    description:
      "We’re just a few minutes’ walk from Busselton Jetty and the waters and beaches of Geographe Bay. Busselton town center is around five minutes away, with its many restaurants and bars and there are several parks to explore. Relax at our heated outdoor pool, enjoy our 24-hour fitness center, or take advantage of our event space for your next meeting.",
    address: "4 Jetty Wy, Busselton WA 6280",
    guestCapacity: 6,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "ttday/554737744_rg2wmy",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216594/ttday/554737744_rg2wmy.jpg",
      },
      {
        public_id: "ttday/perth2_ydqw8r",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216595/ttday/perth2_ydqw8r.webp",
      },
      {
        public_id: "ttday/533339321_tlbitr",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216588/ttday/533339321_tlbitr.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
  {
    name: "Batman's Hill On Collins",
    pricePerNight: 105,
    description:
      "it's located in central city surrounded by shopping centres hotels restaurants and other commercial activities",
    address: "623 Collins St, Melbourne VIC 3000",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "ttday/533339339_r3vker",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216589/ttday/533339339_r3vker.jpg",
      },
      {
        public_id: "ttday/533338975_iljm8u",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216588/ttday/533338975_iljm8u.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Highway One Motel Ceduna",
    pricePerNight: 36,
    description: "We offer you drinks in the middle of the desert.",
    address: "35 Eyre Hwy, Ceduna SA 5690",
    guestCapacity: 2,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "ttday/24837997_z8vbcp",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216586/ttday/24837997_z8vbcp.jpg",
      },
    ],
    category: "Twins",
    reviews: [],
  },
  {
    name: "Swansea Beach Chalets",
    pricePerNight: 82,
    description:
      "Our largest room with a queen bed and foldable sofa. Your only choice on the beautiful island.",
    address: "27 Shaw St, Swansea TAS 7190",
    guestCapacity: 5,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: false,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "ttday/301049606_ibtl7u",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216587/ttday/301049606_ibtl7u.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
  {
    name: "Kalbarri Tudor Holiday Park",
    pricePerNight: 76,
    description: "Sleep with kangaroos.",
    address: "10 Porter St, Kalbarri WA 6536",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "ttday/1754_roqec_02_p_1024x768_mhbugf",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216585/ttday/1754_roqec_02_p_1024x768_mhbugf.jpg",
      },
      {
        public_id: "ttday/1754_ho_00_p_1024x768_ifzvai",
        url: "https://res.cloudinary.com/dewlvunhe/image/upload/v1716216585/ttday/1754_ho_00_p_1024x768_ifzvai.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
];
